### PR TITLE
Another bugfix patch for upstream. Changes:

### PR DESCRIPTION
**Pull request by chaoskagami**
I went through and sorted through what could and couldn't be applied a bit more, so here's another bugfix patch:

Short commit names on 5digits/dactyl are
  bf133a
  fb1355
  58faec
  8da04c
  68b221
  174b8a
  07928b
  079277

I did a few other things to aid testing and perhaps document things better.

I've tested and it works as intended with all of these commits patched in, so it shouldn't cause any issues for people. ;P

### CODE REVIEW

**Comment by wolfbeast** [comment]
Thanks! I won't really be able to personally verify without learning vim, so if any existing pentadactyl users you know of can review the updated version for you that would be great :smile:

**Comment by chaoskagami** [comment]
Unfortunately, I don't know of anyone other than myself who uses it. :/ If anyone finds any issues with the changes, I'll get on it asap. I tested briefly each patch; I squashed it prior to commiting it to github. I was more careful than with the first PR, so it's more likely there's issues with that one if any.

Vim bindings are def complicated. I don't actually use vim for text editing, myself. I do find pentadactyl indispensable since I can access everything with one or two keys, and zero reaching for ctrl or mousing through menus. I spend most of my time on the internet, so the less fighting my touchpad, the better. :P

**Comment by prikhi** [comment]
I now use this! So thank you for your work @chaoskagami :)

**Comment by prikhi** [comment]
If you are interested in documenting your procedure, I might try my hand at some more.

**Comment by chaoskagami** [comment]
This was all done a year ago, so things have changed a lot since. It'll be work to figure out what fixes you can and can't apply, since upstream now uses a lot of FF26+ code and incompatible javascript. But anyways:

Upstream pentadactyl is here: https://github.com/5digits/dactyl - The build process there is a relatively simple copy of the common files and the pentadactyl specific files into an XPI (because the dactyl repo is also melodactyl)

On the other hand, this repo is a modified build of a firefox XPI. There's not really any fancy substitutuion going on so it's possible to look at dactyl's commit history and apply the changes manually which is what I did (although it's not possible to pull commits since there's no common history.) Most of the relevant upstream code is in common and pentadactyl.

Just bear in mind that you can't pull any patches relying on newer spidermonkey syntax or any unimplemented addon APIs (because remember, they don't target FF 26 anymore.) Anything relating to e10s or newer FF is also out. You're going to spend time looking at code that may or may not have been completely refactored or renamed and trying to figure out where things go. Not fun stuff.

To test...`cd` in the extensions folder of your profile and:
`git clone https://github.com/<your fork>/pentadactyl-pm "pentadactyl@addons.palemoon.org"`

Firefox WILL load the repo like a normal extension and this gives the benefit of quick testing.

**Pull request merged**
